import { LayoutWrapper } from "@/components/layouts";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MindMates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <LayoutWrapper>{children}</LayoutWrapper>;
}
